### ISSUE TITLE
Invalid Parameter

### ISSUE THREAD

**Issue by Hacedor2003** [yosle/tropipayjs#7]
Buenas se puede mejorar este error

{
"error": "Invalid Parameter"
}

{
"payload": {
"reference": "pago",
"concept": "baraife",
"favorite": "false",
"amount": "2000",
"currency": "EUR",
"description": "Son productos",
"singleUse": "true",
"reasonId": 10,
"expirationDays": 1,
"lang": "es",
"urlSuccess": "https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e",
"urlFailed": "https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e",
"urlNotification": "https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e",
"serviceDate": "10",
"directPayment": "true"
}
}

**Comment by yosletpp** [comment]
Ese no es el error completo. al reproducir crear un paymentcard con ese payload:

```javascript
TropipayJSException [Error]: Invalid Parameter
    at handleExceptions (/home/yosle/tropipayjs/index.js:48:28)
    at PaymentCard.create (/home/yosle/tropipayjs/index.js:234:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 400,
  error: {
    type: 'VALIDATION_ERROR',
    code: 'INVALID_PARAM',
    message: 'Invalid Parameter',
    details: [
      {
        param: 'urlSuccess',
        value: 'https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e',
        msg: 'Invalid value',
        code: 'INVALID_PARAM',
        location: 'body',
        i18n: 'Parámetros inválidos'
      },
      {
        param: 'urlFailed',
        value: 'https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e',
        msg: 'Invalid value',
        code: 'INVALID_PARAM',
        location: 'body',
        i18n: 'Parámetros inválidos'
      },
      {
        param: 'urlNotification',
        value: 'https: //webhook.site/680826a5-199e-4455-babc-f47b7f26ee7e',
        msg: 'Invalid value',
        code: 'INVALID_PARAM',
        location: 'body',
        i18n: 'Parámetros inválidos'
      }
    ],
    i18n: 'Parámetros inválidos'
  }
}
```

Está claro que varios paramentros son invalidos, los url estan mal escritos

**Comment by Hacedor2003** [comment]
Ah ya
